spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLDB
    username: SYSTEM
    password: 12345

    dbcp2:
      initial-size: 7
      max-total: 20
      pool-prepared-statements: true
flyway.baseline-on-migrate: true