INSERT ALL
INTO CITY VALUES ('kbl', 'af', 'Kabul')
INTO CITY VALUES ('vn', 'au', 'Vienna')
INTO CITY VALUES ('rdj', 'br', 'Rio de Janeiro')
INTO CITY VALUES ('br', 'by', 'Brest')
INTO CITY VALUES ('gml', 'by', 'Gomel')
INTO CITY VALUES ('mn', 'by', 'Minsk')
INTO CITY VALUES ('ber', 'de', 'Berlin')
INTO CITY VALUES ('p', 'fr', 'Paris')
INTO CITY VALUES ('btm', 'ge', 'Batumi')
INTO CITY VALUES ('tb', 'ge', 'Tbilisi')
INTO CITY VALUES ('ath', 'gr', 'Athens')
INTO CITY VALUES ('to', 'jp', 'Tokio')
INTO CITY VALUES ('m', 'ru', 'Moscow')
INTO CITY VALUES ('spb', 'ru', 'Saint Petersburg')
INTO CITY VALUES ('dnp', 'ua', 'Dnipro')
INTO CITY VALUES ('k', 'ua', 'Kyiv')
INTO CITY VALUES ('lv', 'ua', 'Lviv')
INTO CITY VALUES ('l', 'uk', 'London')
INTO CITY VALUES ('la', 'us', 'Los Angeles')
INTO CITY VALUES ('mia', 'us', 'Miami')
INTO CITY VALUES ('ny', 'us', 'New York')
INTO CITY VALUES ('w', 'us', 'Washington')
INTO CITY VALUES ('wsc', 'us', 'Wisconsin')
SELECT * FROM DUAL;